name: Pensieve
version: ${project.version}
main: me.mohamad82.pensieve.Pensieve
api-version: 1.13
authors: [ Mohamad82 ]
description: A well-supported record and replay system in Minecraft!
softdepend:
  - PlaceholderAPI
commands:
  pensieve:
    aliases:
      - pensieve-noreply
  record: